# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: odd_job 
        link: /projects/odd_job
      - name: DMS
        link: /projects/dms
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow us 
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/belfastelixir
      - name: Twitter
        icon: twitter
        link: https://twitter.com/elixirbelfast
    
